<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Drm.Domain\Drm.Domain.csproj" />
    <ProjectReference Include="..\Drm.Application\Drm.Application.csproj" />
    <ProjectReference Include="..\Drm.Infrastructure\Drm.Infrastructure.csproj" />
    <ProjectReference Include="..\Drm.ManagedEngine\Drm.ManagedEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
